// Morpho Blue on Base — the deployment's identity, and deliberately nothing else.
// ----------------------------------------------------------------------------
// Blue is a SINGLETON, not a factory, and it carries the same vanity address on
// every chain it has been deployed to — verified on Base 2026-08-23 (15,623
// bytes of bytecode at the address below, answering `idToMarketParams` for
// every id the census found). So the address is not the interesting part of
// this file; the fact that there is exactly ONE contract, and that a market is
// a parameter tuple rather than a deployment, is.
//
// The roster itself lives in market-catalog.ts beside this, generated by
// scripts/census-morpho-markets.mjs --chain base. It is not written down here
// because it is 4,306 markets long, and it is not resolved at request time
// because Blue exposes no enumeration at all: `idToMarketParams(id)` answers
// only for an id you already hold, and there is no `marketsLength()`. The only
// complete list is the `CreateMarket` log, and that is a census, not a read.
//
// This file stays small on purpose: it is imported by client components, and
// the catalog beside it is 873 KB.

import { BASE_CHAIN_ID } from "@/lib/shared/chains";

/** The Morpho Blue singleton on Base. Same address as Ethereum's — one
 *  contract per chain, and both chains got the same one. */
export const MORPHO_BASE_BLUE = "0xbbbbbbbbbb9cc5e90e3b3af64bdaf62c37eeffcb" as const;

/** The chain every address here lives on. */
export const MORPHO_BASE_CHAIN_ID = BASE_CHAIN_ID;

/** The singleton's first block on Base — the floor of any whole-life event
 *  sweep, and the reason the Base timeline can claim COMPLETENESS rather than
 *  a horizon: the sweep starts here, so there is no earlier singleton activity
 *  for it to have missed. Resolved by bisecting `eth_getCode` at the address
 *  (no code at 13,977,147; code at 13,977,148 — 3 May 2024, 13:40 UTC), which
 *  is self-verifying against any archive node rather than read off a docs
 *  page. The roster's first `CreateMarket` (block 14,500,905) is the upper
 *  bound that check started from. Verified 2026-08-25. */
export const MORPHO_BASE_DEPLOY_BLOCK = 13_977_148;
